In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
# サンプルデータを作ります。
d_range = pd.date_range(start='2020/1/1', end='2020/1/8')
names = ['A', 'B', 'C', 'D']
temp = {'value': [], 'variable': [], 'date': []}

for name in names:
    for day in d_range:
        temp['value'].append(np.random.random())
        temp['variable'].append(name)
        temp['date'].append(day)

dframe = pd.DataFrame(temp)

In [3]:
# 入れ子になったデータができます。
dframe

       value variable       date
0   0.786113        A 2020-01-01
1   0.877453        A 2020-01-02
2   0.398914        A 2020-01-03
3   0.583017        A 2020-01-04
4   0.150861        A 2020-01-05
5   0.368762        A 2020-01-06
6   0.275695        A 2020-01-07
7   0.980983        A 2020-01-08
8   0.395435        B 2020-01-01
9   0.106035        B 2020-01-02
10  0.074729        B 2020-01-03
11  0.419886        B 2020-01-04
12  0.275386        B 2020-01-05
13  0.461320        B 2020-01-06
14  0.371807        B 2020-01-07
15  0.089481        B 2020-01-08
16  0.152733        C 2020-01-01
17  0.203763        C 2020-01-02
18  0.617210        C 2020-01-03
19  0.638368        C 2020-01-04
20  0.904375        C 2020-01-05
21  0.679023        C 2020-01-06
22  0.374175        C 2020-01-07
23  0.772329        C 2020-01-08
24  0.376747        D 2020-01-01
25  0.309210        D 2020-01-02
26  0.008323        D 2020-01-03
27  0.332085        D 2020-01-04
28  0.795795        D 2020-01-05
29  0.293958        D 2020-01-06
30  0.745189        D 2020-01-07
31  0.665986        D 2020-01-08

In [21]:
# 行にdate, 列にvariable、これをvalueで埋めます。
dframe_piv = dframe.pivot(index='date',
                          columns='variable',
                          values='value')
dframe_piv

variable           A         B         C         D
date
2020-01-01  0.428915  0.825524  0.668390  0.328453
2020-01-02  0.780664  0.549194  0.169097  0.625953
2020-01-03  0.216333  0.335612  0.184132  0.222372
2020-01-04  0.834329  0.579061  0.246646  0.025195
2020-01-05  0.456144  0.190938  0.037404  0.763162
2020-01-06  0.012509  0.867858  0.139525  0.888855
2020-01-07  0.116762  0.819224  0.921649  0.696748
2020-01-08  0.956090  0.570040  0.090209  0.126874